# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
	boot = {
		initrd = {
			availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "usb_storage" "sd_mod" ];
  			kernelModules = [ ];
		};
		kernelPackages = pkgs.linuxPackages_latest;
		kernelModules = [ "kvm-intel" ];
		kernelParams = ["i8042.dumbkbd=1"];
		extraModulePackages = [ ];
	};
	fileSystems = {
		"/" = {
			device = "/dev/disk/by-uuid/2b57eb63-3774-45e8-a160-1c17add41793"; 
			fsType = "btrfs";
			options = [ "subvol=root" "compress=zstd" ];
		};
		"/home" = {
			device = "/dev/disk/by-uuid/2b57eb63-3774-45e8-a160-1c17add41793"; 
			fsType = "btrfs";
			options = [ "subvol=home" "compress=zstd"];
		};
		"/nix" = {
			device = "/dev/disk/by-uuid/2b57eb63-3774-45e8-a160-1c17add41793"; 
			fsType = "btrfs";
			options = [ "subvol=nix" "noatime" "compress=zstd"];
		};
		"/boot" = {
			device = "/dev/disk/by-uuid/793E-BDBD";
			fsType = "vfat";
		};
	};

	swapDevices = [ 
		{ device = "/dev/disk/by-uuid/20654296-ad85-49c8-bfea-ceb328aff3d3"; }
    ];

	networking.useDHCP = lib.mkDefault true;
	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
